name: Rust CI & Release

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest  # Windows for winapi
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc
    - name: Build Release
      run: cargo build --verbose --release
    - name: Upload Release Binary
      uses: actions/upload-artifact@v4
      with:
        name: mi-tv-key-blocker.exe
        path: target/release/disable-mi-tv-additional-keys.exe
